server:
  port: ${random.int[10000,30000]}

spring:
  application:
    name: game-rental-app

  datasource:
    url: jdbc:mysql://localhost:3306/game_rental?useUnicode=true&characterEncoding=utf-8&isSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/**
  global-config:
    db-config:
      id-type: ASSIGN_ID