server:
  port: 8080

spring:
  application:
    name: game-rental-app

  datasource:
    url: jdbc:mysql://localhost:3306/game_rental?useUnicode=true&characterEncoding=utf-8&isSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/**
  global-config:
    db-config:
      id-type: ASSIGN_ID

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: game_rental_producer_group


system:
  whitelist:
    ips:
#      - 127.0.0.1
#      - 0:0:0:0:0:0:0:1
    paths:
      - /error
      - /favicon.ico
      - /user/create



logging:
  level:
    org.springframework.security.*: trace