### user add
POST http://localhost:8080/user/create
Content-Type: application/json

{
  "name": "zs",
  "sex": "",
  "mobile": "13565655452",
  "birthday": "2020-10-10"
}


### login
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username = 13550994784 &
password = 1